name: Continuos Integration

on:
  push:
    branches:
      - main  # Será executado apenas no branch main
    paths:
      - 'backend/**'

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17  # Configura o JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages  # Cache para dependências do Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        working-directory: ./backend  # Define a pasta do backend como diretório de trabalho
        run: mvn clean install

      # - name: Run tests
      #   working-directory: ./backend  # Define a pasta do backend como diretório de trabalho
      #   run: mvn test

      - name: set up Doker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub  # Autenticação no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image  # Builda e faz push da imagem para o Docker Hub
        working-directory: ./backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/feedback-academico:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/feedback-academico:latest

      - name: Deploy to Render
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}# Deploy na Render usando imagem Docker
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

      # - name:   # Deploy no Heroku
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.KEY_GERENCIMANETO_FEEDBACK }}  # Usa o segredo adicionado no GitHub
      #   run: |
      #     git remote add heroku https://github.com/Framks/gestao-de-feedback-academico.git
      #     git push heroku HEAD:main
