name: Continuos Integration

on:
  push:
    branches:
      - main

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11  # Configura o JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven packages  # Cache para dependências do Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven  # Build do projeto com Maven
        run: mvn clean install

      - name: Run tests  # Executar testes
        run: mvn test

      - name: Deploy to Heroku  # Deploy no Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.KEY_GERENCIMANETO_FEEDBACK }}  # Usa o segredo adicionado no GitHub
        run: |
          git remote add heroku https://github.com/Framks/gestao-de-feedback-academico.git
          git push heroku HEAD:main
